# Generated by Django 2.0.3 on 2018-03-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('classes', '0002_auto_20180324_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.SchoolClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Student')),
            ],
        ),
    ]
