# Generated by Django 2.0.3 on 2018-03-26 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='semester',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
