# Generated by Django 2.0.3 on 2018-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.PositiveSmallIntegerField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4)]),
        ),
    ]
