# Generated by Django 2.0.3 on 2018-03-25 09:43

from django.db import migrations, models
import django.db.models.deletion
import quizzes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Assignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Question')),
            ],
            bases=(models.Model, quizzes.models.HasAnswerChoices),
        ),
    ]
