# Generated by Django 2.0.3 on 2018-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('IP', 'IN PROGRESS')], default='P', max_length=2),
        ),
    ]
