# Generated by Django 2.0.3 on 2018-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('IP', 'IN PROGRESS'), ('C', 'COMPLETED')], default='P', max_length=2),
        ),
    ]
